#!/usr/bin/env node
/**
 * build.js — reads content/tools/*.md and generates js/tools-data.js
 * Run: node build.js   (or: npm run build)
 *
 * To add a tool: create content/tools/your-tool.md, run build.js, done.
 */

const fs   = require('fs');
const path = require('path');

const TOOLS_DIR = path.join(__dirname, 'content', 'tools');
const OUT_FILE  = path.join(__dirname, 'js', 'tools-data.js');

/* ----------------------------------------------------------
   Parse YAML front-matter + body from a .md file
   ---------------------------------------------------------- */
function parseMd(src) {
  const match = src.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return null;

  const yamlStr = match[1];
  const body    = match[2].trim();
  const meta    = {};

  for (const line of yamlStr.split('\n')) {
    const colon = line.indexOf(':');
    if (colon === -1) continue;

    const key = line.slice(0, colon).trim();
    let   val = line.slice(colon + 1).trim();

    if (!key) continue;

    // quoted string  'value' or "value"
    if (/^['"].*['"]$/.test(val)) {
      meta[key] = val.slice(1, -1);
      continue;
    }

    // array  [a, b, c]  or  [a, 'b', "c"]
    if (val.startsWith('[') && val.endsWith(']')) {
      meta[key] = val.slice(1, -1)
        .split(',')
        .map(s => s.trim().replace(/^['"]|['"]$/g, ''))
        .filter(Boolean);
      continue;
    }

    // boolean
    if (val === 'true')  { meta[key] = true;  continue; }
    if (val === 'false') { meta[key] = false; continue; }

    // number
    if (/^\d+(\.\d+)?$/.test(val)) { meta[key] = Number(val); continue; }

    // plain string
    meta[key] = val;
  }

  return { ...meta, body };
}

/* ----------------------------------------------------------
   Field helpers
   ---------------------------------------------------------- */
const EMOJI_MAP = {
  'gptzero':           '🧠',
  'originality-ai':    '✅',
  'winston-ai':        '🛡️',
  'turnitin-ai':       '🎓',
  'copyleaks':         '🔎',
  'zerogpt':           '🆓',
  'contentatscale':    '📝',
  'passed-ai':         '🏫',
  'sapling-ai':        '🌱',
  'quillbotai-pro':    '🪶',
  'crossplag':         '🌐',
  'openai-classifier': '🤖',
};

function getEmoji(slug) {
  return EMOJI_MAP[slug] || '🔧';
}

/* Build the tagline from subtitle or description first line */
function getTagline(meta) {
  if (meta.subtitle) return meta.subtitle;
  if (meta.description) return meta.description.split('.')[0].trim() + '.';
  return meta.name || '';
}

/* Build full description from body (or fall back to meta.description) */
function getDescription(meta, body) {
  return body || meta.description || '';
}

/* ----------------------------------------------------------
   Main
   ---------------------------------------------------------- */
const files = fs.readdirSync(TOOLS_DIR)
  .filter(f => f.endsWith('.md'))
  .sort();

const tools = [];

for (const file of files) {
  const src  = fs.readFileSync(path.join(TOOLS_DIR, file), 'utf8');
  const data = parseMd(src);

  if (!data) {
    console.warn(`  ⚠  Skipping ${file} — could not parse front-matter`);
    continue;
  }

  const slug = data.slug || file.replace('.md', '');

  tools.push({
    slug,
    name:        data.name  || data.title || slug,
    emoji:       getEmoji(slug),
    tagline:     getTagline(data),
    description: getDescription(data, data.body),
    website:     data.website || '',
    accuracy:    data.accuracy     != null ? Number(data.accuracy)    : null,
    false_pos:   data.false_pos    || data.false_positive || null,
    price:       data.price        || 'Free',
    signup:      data.signup       != null ? data.signup              : true,
    featured:    data.featured     != null ? data.featured            : false,
    rank:        data.rank         != null ? Number(data.rank)        : 99,
    tags:        Array.isArray(data.tags)   ? data.tags               : [],
    top_pick_for: Array.isArray(data.top_pick_for) ? data.top_pick_for : [],
    date:        data.date         || '',
    category:    data.category_name || data.category || 'AI Detection',
  });
}

/* Sort by rank */
tools.sort((a, b) => a.rank - b.rank);

/* ----------------------------------------------------------
   Write output file
   ---------------------------------------------------------- */
const js = `/* AUTO-GENERATED by build.js — do not edit manually.
   To add a tool: create content/tools/your-tool.md, then run: node build.js
   Generated: ${new Date().toISOString()}
*/
const TOOLS = ${JSON.stringify(tools, null, 2)};
`;

fs.writeFileSync(OUT_FILE, js, 'utf8');

console.log(`\n✓ Generated js/tools-data.js`);
console.log(`  ${tools.length} tools from content/tools/\n`);
tools.forEach(t => console.log(`  [${String(t.rank).padStart(2)}] ${t.name}`));
console.log('');
